### ISSUE TITLE
Remove "iTHRIV" from list of "Institutions that may access this resource"

### ISSUE THREAD

**Issue by ajlouie** [uvasomrc/ithriv#68]
iTHRIV is not a login type (distinct user group) so doesn't apply to this function.

**Comment by ajlouie** [comment]
- [ ] Add `hideAvailability` (or something similar) field to schema that prevents an Institution from being included in Availabilities
- [ ] Modify endpoint(s) to filter out `hideAvailability = true` Institutions

**Comment by eleanorgraham** [comment]
fixed in PR #67
