### ISSUE TITLE
Move VISIT WEBSITE and CATEGORIES to top of Information box

### ISSUE THREAD

**Issue by ajlouie** [uvasomrc/ithriv#70]
Adjust resource page interface so that VISIT WEBSITE and CATEGORIES appear toward top of the information box to the side.  Also, these items should clearly be buttons and stand out from other things that just report values (like type, institutions, etc.).  Multiple new users have trouble identifying these things as links when I watch them use the system.  After trying to click on other words in that box, they give up and don't keep trying to click around.  Navigating back to category and going to website are essential features!

**Comment by eleanorgraham** [comment]
fixed in PR #66
