### ISSUE TITLE
Hide unapproved resources for regular (non-admin) users in Search

### ISSUE THREAD

**Issue by ajlouie** [uvasomrc/ithriv#71]
Regular users see unapproved resources when they use the search.  For example, a regular user can search iTHRIV and see iTHRIV Partnership Manager and 16 other unapproved resources.  They can click into the resource page, but once they click on iTHRIV Admin category link, they get taken to an empty category (as there are no approved resources in that category).

**Comment by eleanorgraham** [comment]
Fixed in PR #64
